package cn.ucai.ttmusic.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.ucai.ttmusic.model.db.Music;
import cn.ucai.ttmusic.model.db.MusicList;

import cn.ucai.ttmusic.model.db.MusicDao;
import cn.ucai.ttmusic.model.db.MusicListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicDaoConfig;
    private final DaoConfig musicListDaoConfig;

    private final MusicDao musicDao;
    private final MusicListDao musicListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        musicListDaoConfig = daoConfigMap.get(MusicListDao.class).clone();
        musicListDaoConfig.initIdentityScope(type);

        musicDao = new MusicDao(musicDaoConfig, this);
        musicListDao = new MusicListDao(musicListDaoConfig, this);

        registerDao(Music.class, musicDao);
        registerDao(MusicList.class, musicListDao);
    }
    
    public void clear() {
        musicDaoConfig.clearIdentityScope();
        musicListDaoConfig.clearIdentityScope();
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

    public MusicListDao getMusicListDao() {
        return musicListDao;
    }

}
