package cn.ucai.ttmusic.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MUSIC".
*/
public class MusicDao extends AbstractDao<Music, Long> {

    public static final String TABLENAME = "MUSIC";

    /**
     * Properties of entity Music.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SongId = new Property(1, int.class, "songId", false, "SONG_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "SONG_TITLE");
        public final static Property Singer = new Property(3, String.class, "singer", false, "SONG_SINGER");
        public final static Property Album = new Property(4, String.class, "album", false, "SONG_ALBUM");
        public final static Property AlbumId = new Property(5, int.class, "albumId", false, "SONG_ALBUM_ID");
        public final static Property Url = new Property(6, String.class, "url", false, "SONG_URL");
        public final static Property Size = new Property(7, long.class, "size", false, "SONG_SIZE");
        public final static Property Time = new Property(8, long.class, "time", false, "SONG_TIME");
        public final static Property Name = new Property(9, String.class, "name", false, "SONG_NAME");
        public final static Property IsCollected = new Property(10, int.class, "isCollected", false, "IS_COLLECTED");
        public final static Property CollectTime = new Property(11, long.class, "collectTime", false, "CollectTime");
        public final static Property ListName = new Property(12, String.class, "listName", false, "LIST_NAME");
        public final static Property AddTime = new Property(13, long.class, "addTime", false, "ADD_TIME");
    }


    public MusicDao(DaoConfig config) {
        super(config);
    }
    
    public MusicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MUSIC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SONG_ID\" INTEGER NOT NULL UNIQUE ," + // 1: songId
                "\"SONG_TITLE\" TEXT," + // 2: title
                "\"SONG_SINGER\" TEXT," + // 3: singer
                "\"SONG_ALBUM\" TEXT," + // 4: album
                "\"SONG_ALBUM_ID\" INTEGER NOT NULL ," + // 5: albumId
                "\"SONG_URL\" TEXT," + // 6: url
                "\"SONG_SIZE\" INTEGER NOT NULL ," + // 7: size
                "\"SONG_TIME\" INTEGER NOT NULL ," + // 8: time
                "\"SONG_NAME\" TEXT," + // 9: name
                "\"IS_COLLECTED\" INTEGER NOT NULL ," + // 10: isCollected
                "\"CollectTime\" INTEGER NOT NULL ," + // 11: collectTime
                "\"LIST_NAME\" TEXT," + // 12: listName
                "\"ADD_TIME\" INTEGER NOT NULL );"); // 13: addTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MUSIC\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Music entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSongId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String singer = entity.getSinger();
        if (singer != null) {
            stmt.bindString(4, singer);
        }
 
        String album = entity.getAlbum();
        if (album != null) {
            stmt.bindString(5, album);
        }
        stmt.bindLong(6, entity.getAlbumId());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
        stmt.bindLong(8, entity.getSize());
        stmt.bindLong(9, entity.getTime());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(10, name);
        }
        stmt.bindLong(11, entity.getIsCollected());
        stmt.bindLong(12, entity.getCollectTime());
 
        String listName = entity.getListName();
        if (listName != null) {
            stmt.bindString(13, listName);
        }
        stmt.bindLong(14, entity.getAddTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Music entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSongId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String singer = entity.getSinger();
        if (singer != null) {
            stmt.bindString(4, singer);
        }
 
        String album = entity.getAlbum();
        if (album != null) {
            stmt.bindString(5, album);
        }
        stmt.bindLong(6, entity.getAlbumId());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
        stmt.bindLong(8, entity.getSize());
        stmt.bindLong(9, entity.getTime());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(10, name);
        }
        stmt.bindLong(11, entity.getIsCollected());
        stmt.bindLong(12, entity.getCollectTime());
 
        String listName = entity.getListName();
        if (listName != null) {
            stmt.bindString(13, listName);
        }
        stmt.bindLong(14, entity.getAddTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Music readEntity(Cursor cursor, int offset) {
        Music entity = new Music( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // songId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // singer
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // album
            cursor.getInt(offset + 5), // albumId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // url
            cursor.getLong(offset + 7), // size
            cursor.getLong(offset + 8), // time
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // name
            cursor.getInt(offset + 10), // isCollected
            cursor.getLong(offset + 11), // collectTime
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // listName
            cursor.getLong(offset + 13) // addTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Music entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSongId(cursor.getInt(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSinger(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAlbum(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAlbumId(cursor.getInt(offset + 5));
        entity.setUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSize(cursor.getLong(offset + 7));
        entity.setTime(cursor.getLong(offset + 8));
        entity.setName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setIsCollected(cursor.getInt(offset + 10));
        entity.setCollectTime(cursor.getLong(offset + 11));
        entity.setListName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setAddTime(cursor.getLong(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Music entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Music entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Music entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
